export const tShirts = [
  {
    id: 1,
    name: "Oversized Graphic Print T-Shirt",
    category: "Oversized",
    subCategory: "Graphic Printed",
    description:
      "Black oversized t-shirt with bold graphic print. Made from 100% cotton.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "100% Cotton",
    image:
      "https://i.pinimg.com/564x/3a/4c/3b/3a4c3b9e6a7f8d9e5f6c7b8a9d0e1f2.jpg",
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 2,
    name: "Acid Wash Distressed Tee",
    category: "Acid Wash",
    subCategory: "Graphic Printed",
    description:
      "Vintage acid wash t-shirt with distressed details and graphic print.",
    sizes: ["S", "M", "L"],
    colors: ["Light Blue"],
    material: "100% Cotton",
    image:
      "https://i.pinimg.com/564x/4b/5c/6d/4b5c6d9e8f7a6b5c4d3e2f1g0h9i8j.jpg",
    price: 27.99,
    originalPrice: 34.99,
    rating: 4.3,
    inStock: true,
  },
  {
    id: 3,
    name: "Classic Polo Shirt",
    category: "Polo T-Shirts",
    subCategory: "Solid Color",
    description: "Premium cotton polo with three-button placket.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy"],
    material: "100% Pima Cotton",
    image:
      "https://i.pinimg.com/564x/5c/6d/7e/5c6d7e9f8a7b6c5d4e3f2g1h0i9j8.jpg",
    price: 32.99,
    originalPrice: 39.99,
    rating: 4.7,
    inStock: true,
  },
  {
    id: 4,
    name: "Sleeveless Muscle Tee",
    category: "Sleeveless",
    subCategory: "Solid Color",
    description: "Performance sleeveless shirt for workouts.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "95% Cotton, 5% Spandex",
    image: "https://i.pinimg.com/564x/6d/7e/8f/6d7e8f9a8b7c6d5e4f3g2h1i0j9.jpg",
    price: 19.99,
    originalPrice: 24.99,
    rating: 4.2,
    inStock: true,
  },
  {
    id: 5,
    name: "Oversized Hooded Tee",
    category: "Hooded",
    subCategory: "Oversized",
    description: "Comfortable hooded oversized t-shirt.",
    sizes: ["M", "L", "XL"],
    colors: ["Gray"],
    material: "80% Cotton, 20% Polyester",
    image: "https://i.pinimg.com/564x/7e/8f/9a/7e8f9a8b7c6d5e4f3g2h1i0j9k8.jpg",
    price: 36.99,
    originalPrice: 44.99,
    rating: 4.6,
    inStock: true,
  },
  {
    id: 6,
    name: "Henley Long Sleeve",
    category: "Henley",
    subCategory: "Long Sleeve",
    description: "Button-up henley neck in soft cotton.",
    sizes: ["S", "M", "L"],
    colors: ["Heather Gray"],
    material: "100% Organic Cotton",
    image: "https://i.pinimg.com/564x/8f/9a/bc/8f9abc7d6e5f4g3h2i1j0k9l8.jpg",
    price: 22.99,
    originalPrice: 27.99,
    rating: 4.4,
    inStock: true,
  },
  {
    id: 7,
    name: "Minimalist Oversized Tee",
    category: "Oversized",
    subCategory: "Solid Color",
    description: "Simple oversized t-shirt in premium fabric.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White"],
    material: "100% Combed Cotton",
    image: "https://i.pinimg.com/564x/9a/bc/de/9abcde6f5g4h3i2j1k0l9m8.jpg",
    price: 21.99,
    originalPrice: 25.99,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 8,
    name: "Acid Wash Polo",
    category: "Polo T-Shirts",
    subCategory: "Acid Wash",
    description: "Distressed acid wash polo shirt.",
    sizes: ["S", "M", "L"],
    colors: ["Light Blue"],
    material: "65% Cotton, 35% Polyester",
    image: "https://i.pinimg.com/564x/bc/de/f1/bcdef1g2h3i4j5k6l7m8n9.jpg",
    price: 31.99,
    originalPrice: 37.99,
    rating: 4.1,
    inStock: true,
  },
  {
    id: 9,
    name: "Athletic Sleeveless",
    category: "Sleeveless",
    subCategory: "Performance",
    description: "Moisture-wicking sleeveless athletic shirt.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "90% Polyester, 10% Spandex",
    image: "https://i.pinimg.com/564x/de/f1/23/def123g4h5i6j7k8l9m0n1.jpg",
    price: 22.99,
    originalPrice: 26.99,
    rating: 4.7,
    inStock: true,
  },
  {
    id: 10,
    name: "Graphic Hoodie",
    category: "Hooded",
    subCategory: "Graphic Printed",
    description: "Streetwear hoodie with bold graphic print.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "80% Cotton, 20% Polyester",
    image: "https://i.pinimg.com/564/f1/23/45/f12345g6h7i8j9k0l1m2n3.jpg",
    price: 35.99,
    originalPrice: 42.99,
    rating: 4.3,
    inStock: true,
  },
];
